load("//Config:buck_rule_macros.bzl", "apple_lib")

apple_lib(
    name = "SwiftAndObjc",
    exported_headers = glob([
      "*.h",
      ]),
    srcs = glob([
        "*.swift",
        "*.m"
    ]),
)
