load("//:xcode_settings.bzl", "DEFAULT_CONFIGS")
load("//:buck_rules.bzl", "apple_lib", "apple_test_lib")


# empty build rule to force Buck build libraries
apple_library(
  name = 'Test',
  swift_version = '4',
  srcs = glob([
    'Test/*.swift',
  ]),
  deps = [
    '//src/ImportFromAnotherLibrary:ImportFromAnotherLibrary',
    '//Pods:Braintree',
    # '//Pods:Nimble',
    '//Pods:PromiseKit',
    # '//Pods:Quick',
  ],
  frameworks = [
    '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
  ],
)

apple_test_lib(
  name = 'AppTests',
  visibility = ['PUBLIC'],
  srcs = [
    'TestTests/TestTests.swift'
  ],
  info_plist = "TestTests/Info.plist",
  deps = [
    ':Test'
  ],
  frameworks = [
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework",
    ],
)

apple_asset_catalog(
  name = 'TestAssets',
  dirs = [
    'Test/Assets.xcassets',
  ]
)

apple_resource(
  name = 'TestResources',
  files = glob([
    'Test/DummyResource.txt',
  ]),
  dirs = [
    'Test/DummyResourceDir',
  ],
)

apple_binary(
  name = 'TestBinary',
  visibility = ['PUBLIC'],
  configs = DEFAULT_CONFIGS,
  deps = [
    # main binary
    ':Test',

    # resource
    ':TestResources',

    # assets
    ':TestAssets',
  ],
)

apple_package(
  name = 'TestsPackage',
  bundle = ':TestApp',
)

apple_bundle(
  name = 'TestApp',
  product_name = 'Test',
  binary = ':TestBinary',
  extension = 'app',
  info_plist = 'Test/Info.plist',
  info_plist_substitutions = {
    'PRODUCT_BUNDLE_IDENTIFIER': 'com.test.testapp',
  },
)
