load("//:xcode_settings.bzl", "DEFAULT_CONFIGS")
load("//:buck_rules.bzl", "apple_lib", "apple_test_lib")


# empty build rule to force Buck build libraries
apple_library(
  name = 'BuckSampleLibrary',
  visibility = ['PUBLIC'],
  modular = True,
  swift_version = '4',
  srcs = [
    'ViewController.swift',
    'AppDelegate.swift'
  ],
  deps = [
    # '//src/ImportFromAnotherLibrary:ImportFromAnotherLibrary',
    # '//Pods:Braintree',
    # '//Pods:Nimble',
    # '//Pods:PromiseKit',
    # '//Pods:Quick',
  ],
  # tests = ['//BuckSampleTests:BuckSampleTests']
)


apple_asset_catalog(
  name = 'Assets',
  dirs = [
    'Assets.xcassets',
  ]
)

# dummary target for example
apple_resource(
  name = 'Resources',
  files = glob([
    'DummyResource.txt',
  ]),
  dirs = [
    'DummyResourceDir',
  ],
)

xcode_workspace_config(
  name = 'lib_workspace',
  workspace_name = 'BuckSample',
  src_target = ':BuckSampleLibrary',
  extra_tests = ['//BuckSampleTests:BuckSampleTests'],
)

xcode_workspace_config(
  name = 'workspace',
  workspace_name = 'BuckSampleApp',
  src_target = ':BuckSampleBundle',
  extra_schemes = {'BuckSample': ':lib_workspace'},
  additional_scheme_actions = {
    'Build': {
      'PRE_SCHEME_ACTIONS': ['echo \'Started\''],
      'POST_SCHEME_ACTIONS': ['echo \'Finished\''],
      }
  },
)

apple_binary(
  name = 'BuckSampleBinary',
  visibility = ['PUBLIC'],
  configs = DEFAULT_CONFIGS,
  # srcs = ['main.swift'],
  deps = [
    # main binary
    ':BuckSampleLibrary',

    # resource
    ':Resources',

    # assets
    ':Assets',
  ],
)

apple_bundle(
  name = 'BuckSampleBundle',
  visibility = ['PUBLIC'],
  extension = 'app',
  binary = ':BuckSampleBinary',
  product_name = 'BuckSample',
  info_plist = 'Info.plist',
  info_plist_substitutions = {
    'PRODUCT_BUNDLE_IDENTIFIER': 'com.company.samplebuck',
    'PRODUCT_NAME': 'BuckSample',
    "EXECUTABLE_NAME": "BuckSample",
  },
  deps = [':BuckSampleBinary'],
)

apple_package(
  name = 'BuckSamplePackage',
  bundle = ':BuckSampleBundle',
)
