load("//:xcode_settings.bzl", "DEFAULT_CONFIGS")
load("//:buck_rules.bzl", "apple_lib", "apple_test_lib")


# empty build rule to force Buck build libraries
apple_library(
  name = 'BuckSampleLibrary',
  swift_version = '4',
  srcs = glob([
    'Test/*.swift',
  ]),
  deps = [
    '//src/ImportFromAnotherLibrary:ImportFromAnotherLibrary',
    # '//Pods:Braintree',
    # '//Pods:Nimble',
    # '//Pods:PromiseKit',
    # '//Pods:Quick',
  ],
)


apple_asset_catalog(
  name = 'Assets',
  dirs = [
    'Assets.xcassets',
  ]
)

# dummary target for example
apple_resource(
  name = 'Resources',
  files = glob([
    'DummyResource.txt',
  ]),
  dirs = [
    'DummyResourceDir',
  ],
)

xcode_workspace_config(
  name = 'workspace',
  src_target = ':BuckSampleBundle'
)

apple_binary(
  name = 'BuckSampleBinary',
  visibility = ['PUBLIC'],
  configs = DEFAULT_CONFIGS,
  srcs = ['main.swift'],
  deps = [
    # main binary
    ':BuckSampleLibrary',

    # resource
    ':Resources',

    # assets
    ':Assets',
  ],
)

apple_bundle(
  name = 'BuckSampleBundle',
  extension = 'app',
  binary = ':BuckSampleBinary',
  product_name = 'BuckSample',
  info_plist = 'Info.plist',
  info_plist_substitutions = {
    'PRODUCT_BUNDLE_IDENTIFIER': 'com.company.samplebuck',
    'PRODUCT_NAME': 'BuckSample',
    "EXECUTABLE_NAME": "BuckSample",
  },
)

apple_package(
  name = 'BuckSamplePackage',
  bundle = ':BuckSampleBundle',
)
