load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "SecondSwiftModule",
    deps = [
        "//Libraries/YetAnotherSwiftModule:YetAnotherSwiftModule",
    ],
    test_deps = [
        "//Pods:Quick",
        "//Pods:Nimble",
    ],
)
