load("//Config:buck_rule_macros.bzl", "apple_lib")

apple_lib(
    name = "Objc1",
    visibility = ["PUBLIC"],
    modular = True,
    exported_headers = [
      "ObjcClass1.h",
      ],
    srcs = [
        "ObjcClass1.m"
    ],
    extra_xcode_files = [
        "Objc1.modulemap",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
