load("//Config:buck_rule_macros.bzl", "first_party_library", "mlmodel_resource")

first_party_library(
    name = "SwiftWithMLModel",
    mlmodel_generated_source = [
        ":MarsHabitatPricerInterface",
    ],
    deps = [
        ":MarsHabitatPricerMLModel",
    ],
)

mlmodel_resource(
    resource_source_name = "MarsHabitatPricerInterface",
    resource_dependency_name = "MarsHabitatPricerMLModel",
    model_directory = "Resources/",
    model_name = "MarsHabitatPricer"
)