load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")
load("//Config:configs.bzl", "library_configs")

apple_lib(
    name = "ImportObjC",
    exported_headers = glob([
        "**/*.h",
    ]),
    srcs = glob([
        "*.swift",
        "folderA/*.m",
        "folderB/*.m",
    ]),
    tests = [":Tests"],
)


apple_test_lib(
    name = "Tests",
    srcs = glob([
        "Tests/*.swift",
    ]),
    info_plist = "Tests/Info.plist",
    deps = [
        ":ImportObjC",
    ],
)
