load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "SwiftWithPrecompiledDependency",
    deps = [
        "//Pods:AFNetworking",
    ],
    test_deps = [
        # Explicitly add the precompiled library to the test's dependencies to prevent a crash when running this test target in CLI.
        "//Pods:AFNetworking",
    ]
)
