load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "Cpp1",
    has_cpp = True,
    extra_xcode_files = [
        "Cpp1.modulemap",
    ],
    internal_headers = [
      "Sources/util.hpp",
    ]
)
