load("//:buck_rules.bzl", "apple_lib")

apple_lib(
  name = 'ImportObjC',
  visibility = ['PUBLIC'],
  modular = True,
  exported_headers = glob([
    '**/*.h',
  ]),
  srcs = glob([
    '**/*.m',
    '**/*.swift',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
