apple_library(
  name = 'ImportObjC',
  visibility = ['PUBLIC'],
  exported_headers = glob([
    '**/*.h',
  ]),
  srcs = glob([
    '**/*.m',
    '**/*.swift',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
