load("//Config:buck_local.bzl", "buck_local_apple_resource")

buck_local_apple_resource(
    name = "ExampleAppStringResources",
    visibility = ["//App:"],
    files = [],
    variants = glob([
        "*.lproj/ExampleApp.strings",
    ]),
)

buck_local_apple_resource(
    name = "StoryboardResources",
    visibility = ["//App:"],
    variants = glob([
        "*.lproj/*.storyboard",
    ]),
)
