load("//Config:buck_rule_macros.bzl", "intentdefinition_resource")

apple_resource(
    name = "ExampleAppStringResources",
    visibility = ["//App:"],
    files = [],
    variants = glob([
        "*.lproj/ExampleApp.strings",
    ]),
)

apple_resource(
    name = "StoryboardResources",
    visibility = ["//App:"],
    variants = glob([
        "*.lproj/*.storyboard",
    ]),
)

intentdefinition_resource("IntentsDefinition", "./en.lproj/", "Intents",  "en")
