load("//Config:buck_rule_macros.bzl", "apple_lib")

apple_lib(
    name = "Swift4",
    visibility = ["PUBLIC"],
    modular = True,
    srcs = glob([
        "**/*.swift",
    ]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
