load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")

apple_lib(
    name = "Swift3",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//Libraries/Swift4:Swift4",
    ],
    tests = [
        ":Swift3Tests",
    ],
)

apple_test_lib(
    name = "Swift3Tests",
    srcs = glob([
        "Tests/**/*.swift",
    ]),
    info_plist = "Tests/Info.plist",
    deps = [
        ":Swift3",
    ],
)
