load("//Config:buck_rule_macros.bzl", "library")

library(
    name = "SwiftWithAssets",
    deps = [
        ":SwiftWithAssetsCatalog",
    ],
)

apple_asset_catalog(
    name = "SwiftWithAssetsCatalog",
    visibility = ["PUBLIC"],
    dirs = ["Resources/Catalog.xcassets"],
)
