load("//Config:buck_rule_macros.bzl", "first_party_library")
load("//Config:buck_local.bzl", "buck_local_apple_asset_catalog")

first_party_library(
    name = "SwiftWithAssets",
    deps = [
        ":SwiftWithAssetsCatalog",
    ],
)

buck_local_apple_asset_catalog(
    name = "SwiftWithAssetsCatalog",
    visibility = ["PUBLIC"],
    dirs = ["Resources/Catalog.xcassets"],
)
