load("//:xcode_settings.bzl", "DEFAULT_CONFIGS")
load("//:buck_rules.bzl", "apple_lib", "apple_test_lib")

apple_test_lib(
  name = 'BuckSampleTests',
  visibility = ['PUBLIC'],
  srcs = [
    'BuckSampleTests.swift'
  ],
  info_plist = "Info.plist",
  deps = [
    '//BuckSample:BuckSampleLibrary'
  ],
)
