load("//Config:configs.bzl", "binary_configs", "library_configs", "pretty", "info_plist_substitutions")
load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")

apple_asset_catalog(
    name = "ExampleAppAssets",
    visibility = ["PUBLIC"],
    app_icon = "AppIcon",
    dirs = ["Assets.xcassets"],
)

apple_resource(
    name = "ExampleAppResource",
    visibility = ["PUBLIC"],
    files = glob(["**/*.storyboard"]),
)

apple_binary(
    name = "ExampleAppBinary",
    visibility = ["PUBLIC"],
    configs = binary_configs("ExampleApp"),
    swift_version = "4.2",
    srcs = [
        "ViewController.swift",
        "AppDelegate.swift",
    ],
    tests = [
        "//App/Tests:Tests",
    ],
    deps = [
        "//Libraries/Swift2:Swift2",
        "//Libraries/Swift3:Swift3",
        "//Libraries/Objc1:Objc1",
        "//Pods:CryptoSwift",
        "//Pods:OHHTTPStubs",
        ":ExampleAppResource",
        ":ExampleAppAssets",
    ],
)

xcode_workspace_config(
    name = "workspace",
    workspace_name = "ExampleApp",
    src_target = ":ExampleAppBundle",
    additional_scheme_actions = {
        "Build": {
            "PRE_SCHEME_ACTIONS": ["echo 'Started'"],
            "POST_SCHEME_ACTIONS": ["echo 'Finished'"],
        },
    },
    action_config_names = {"profile": "Profile"},
)

apple_bundle(
    name = "ExampleAppBundle",
    visibility = ["PUBLIC"],
    extension = "app",
    binary = ":ExampleAppBinary",
    product_name = "ExampleApp",
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions("ExampleApp"),
)

apple_package(
    name = "ExampleAppPackage",
    bundle = ":ExampleAppBundle",
)
