apple_library(
  name = 'ImportFromAnotherLibrary',
  visibility = ['PUBLIC'],
  modular = True,
  exported_headers = glob([
    '**/*.h',
  ]),
  srcs = glob([
    '**/*.m',
    '**/*.swift',
  ]),
  deps = [
    '//src/ImportObjC:ImportObjC',
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
