load("//Config:buck_rule_macros.bzl", "apple_lib")

apple_lib(
    name = "ImportFromAnotherLibrary",
    exported_headers = glob([
        "**/*.h",
    ]),
    srcs = glob([
        "**/*.m",
        "**/*.swift",
    ]),
    deps = [
        "//Libraries/ImportObjC:ImportObjC",
    ],
)
