load("//Config:buck_rule_macros.bzl", "apple_lib")

apple_lib(
    name = "ImportFromAnotherLibrary",
    visibility = ["PUBLIC"],
    modular = True,
    exported_headers = glob([
        "**/*.h",
    ]),
    srcs = glob([
        "**/*.m",
        "**/*.swift",
    ]),
    deps = [
        "//Libraries/ImportObjC:ImportObjC",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
