load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")
load("//Config:frameworks.bzl", "first_party_frameworks")

apple_test_lib(
    name = "Tests",
    srcs = glob([
        "*.swift",
    ]),
    info_plist = "Info.plist",
    deps = first_party_frameworks + [
        "//App:ExampleApp",
    ],
)
