load("//:buck_rules.bzl", "apple_lib", "apple_test_lib")

apple_test_lib(
    name = "Tests",
    visibility = ["PUBLIC"],
    srcs = glob([
        "*.swift",
    ]),
    info_plist = "Info.plist",
    deps = [
        "//App:ExampleAppLibrary",
    ],
)
