load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")

apple_test_lib(
    name = "UITests",
    visibility = ["PUBLIC"],
    test_host_app = "//App:ExampleAppBundle",
    srcs = [
        "BuckSampleUITests.swift",
    ],
    info_plist = "Info.plist",
    labels = ['ui'],
    deps = [
        "//Libraries/Swift1:Swift1",
    ],
)
