load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib")

apple_test_lib(
    name = "UITests",
    test_host_app = "//App:ExampleApp",
    srcs = [
        "BuckSampleUITests.swift",
    ],
    info_plist = "Info.plist",
    labels = ['ui'],
    deps = [
        "//Libraries/Swift2:Swift2",
    ],
)
